[opener]
edit = [
    { run = 'nvim "$@"', block = true },
]
play = [
    { run = 'open "$@"', orphan = true, for = "unix" },
]
open = [
    { run = 'open "$@"', desc = "Open with default application", for = "unix" },
]

reveal = [
  { run = 'open -R "$1"',                         desc = "Reveal", for = "macos" },
]

extract = [
	{ run = 'ya pub extract --list "$@"', desc = "Extract here", for = "unix" },
]

zathura = [
    { run = 'zathura "$@" &', desc = "Open with Zathura", for = "unix" },
]

[open]
rules = [
    { name = "*.pdf", use = ["zathura","reveal"] },
    { name = "*.html", use =  "edit"  },
    { name = "*/", use = [  "open", "edit", "reveal" ] },
    # Text
	  { mime = "text/*", use = [ "edit", "reveal" ] },
	  # Image
	  { mime = "image/*", use = [ "open", "reveal" ] },
	  # Media
	  { mime = "{audio,video}/*", use = [ "play", "reveal" ] },
	  # Archive
	  { mime = "application/{,g}zip", use = [ "extract", "reveal" ] },
	  { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", use = [ "extract", "reveal" ] },
	  # JSON
	  { mime = "application/{json,x-ndjson}", use = [ "edit", "reveal" ] },
	  { mime = "*/javascript", use = [ "edit", "reveal" ] },
	  # Empty file
	  { mime = "inode/x-empty", use = [ "edit", "reveal" ] },
	  # Fallback
	  { name = "*", use = [ "open", "reveal" ] },
]

[plugin]
prepend_previewers = [
    { mime = "{image,audio,video}/*", run = "mediainfo"},
    { mime = "application/x-subrip", run = "mediainfo"},
    { name = "*.md", run = "glow" },

]
