# format = """
# [](#a3aed2)\
# [ ](bg:#a3aed2 fg:#090c0c)\
# [](bg:#769ff0 fg:#a3aed2)\
# $directory\
# [](fg:#769ff0 bg:#394260)\
# $git_branch\
# $git_status\
# [](fg:#394260 )\
# \n$character"""
#
# [directory]
# style = "fg:#e3e5e5 bg:#769ff0"
# format = "[ $path ]($style)"
# truncation_length = 1
# truncation_symbol = "…/"
#
# [directory.substitutions]
# "Documents" = "󰈙 "
# "Downloads" = " "
# "Music" = " "
# "Pictures" = " "
#
# [git_branch]
# symbol = ""
# style = "bg:#394260"
# format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'
#
# [git_status]
# style = "bg:#394260"
# format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'
#
#
# [time]
# disabled = true
# time_format = "%R" # Hour:Minute Format
# style = "bg:#1d2230"
# format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'
#
#
#
#
#################### FOR gruvbox_dark  ######################

# format = """
# [](color_orange)\
# $os\
# [](bg:color_yellow fg:color_orange)\
# $directory\
# [](fg:color_yellow bg:color_aqua)\
# $git_branch\
# $git_status\
# [](fg:color_aqua bg:color_bg1 )\
# [ ](fg:color_bg1)\
# $line_break$character"""
#
# palette = 'gruvbox_dark'
#
# [palettes.gruvbox_dark]
# color_fg0 = '#fbf1c7'
# color_bg1 = '#3c3836'
# color_bg3 = '#665c54'
# color_blue = '#458588'
# color_aqua = '#689d6a'
# color_green = '#98971a'
# color_orange = '#d65d0e'
# color_purple = '#b16286'
# color_red = '#cc241d'
# color_yellow = '#d79921'
#
# [os]
# disabled = false
# style = "bg:color_orange fg:color_fg0"
#
# [os.symbols]
# Macos = "󰀵"
#
#
# [directory]
# style = "fg:color_fg0 bg:color_yellow"
# format = "[ $path ]($style)"
# truncation_length = 1
# truncation_symbol = "…/"
#
# [directory.substitutions]
# "Documents" = "󰈙 "
# "Downloads" = " "
# "Music" = "󰝚 "
# "Pictures" = " "
# "Developer" = "󰲋 "
#
# [git_branch]
# symbol = ""
# style = "bg:color_aqua"
# format = '[[ $symbol $branch ](fg:color_fg0 bg:color_aqua)]($style)'
#
# [git_status]
# style = "bg:color_aqua"
# format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:color_aqua)]($style)'
#
# [nodejs]
# symbol = ""
# style = "bg:color_blue"
# format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
#
# [c]
# symbol = " "
# style = "bg:color_blue"
# format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
#
# [rust]
# symbol = ""
# style = "bg:color_blue"
# format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
#
# [golang]
# symbol = ""
# style = "bg:color_blue"
# format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
#
# [php]
# symbol = ""
# style = "bg:color_blue"
# format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
#
# [java]
# symbol = " "
# style = "bg:color_blue"
# format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
#
# [kotlin]
# symbol = ""
# style = "bg:color_blue"
# format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
#
# [haskell]
# symbol = ""
# style = "bg:color_blue"
# format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
#
# [python]
# symbol = ""
# style = "bg:color_blue"
# format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
#
# [docker_context]
# symbol = ""
# style = "bg:color_bg3"
# format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'
#
# [conda]
# style = "bg:color_bg3"
# format = '[[ $symbol( $environment) ](fg:#83a598 bg:color_bg3)]($style)'
#
#
# [line_break]
# disabled = false
#
# [character]
# disabled = false
# success_symbol = '[](bold fg:color_green)'
# error_symbol = '[](bold fg:color_red)'
# vimcmd_symbol = '[](bold fg:color_green)'
# vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
# vimcmd_replace_symbol = '[](bold fg:color_purple)'
# vimcmd_visual_symbol = '[](bold fg:color_yellow)'
#
# ######################## PURE ###########################
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""


[directory]
style = "blue"
truncation_length = 1
truncation_symbol = "…/"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"
