#!/bin/bash
# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"
source "$CONFIG_DIR/colors.sh" # Loads all defined colors

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar height=27 \
  blur_radius=30 \
  position=bottom sticky=on \
  padding_left=0 \
  margin=10 \
  padding_right=0 corner_radius=5 color=$BAR_COLOR

##### Changing Defaults #####
# We now change some default values that are applied to all further items
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

sketchybar --default icon.font="SF Pro:Semibold:15.0" \
  icon.color=$WHITE \
  label.font="SF Pro:Semibold:15.0" \
  label.color=$WHITE \
  background.color=$ITEM_BG_COLOR \
  background.corner_radius=5 \
  background.height=24 \
  padding_left=5 \
  padding_right=5 \
  label.padding_left=4 \
  label.padding_right=10 \
  icon.padding_left=10 \
  icon.padding_right=4

sketchybar --add event aerospace_workspace_change

for sid in $(aerospace list-workspaces --all); do
  sketchybar --add item space.$sid left \
    --subscribe space.$sid aerospace_workspace_change \
    --set space.$sid \
    background.color=0xff414868 \
    background.corner_radius=5 \
    background.height=20 \
    background.drawing=off label="$sid" \
    label.padding_left=10 \
    label.padding_right=10 \
    icon.padding_left=0 \
    icon.padding_right=0 \
    click_script="aerospace workspace $sid" \
    script="$CONFIG_DIR/plugins/aerospace.sh $sid"
done

# -- Left Side Items --
# source $ITEM_DIR/spaces.sh
source $ITEM_DIR/front_app.sh

# -- Middle Side Of Notch Items --
source $ITEM_DIR/media.sh

# -- Right Side Items --
source $ITEM_DIR/calendar.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/cpu.sh
# source $ITEM_DIR/memory.sh

sketchybar --update
sketchybar --hotload true
