

import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]

[env]
TERM = "xterm-256color"

[cursor.style]
shape = "Beam"
blinking = "Always"
   

[shell]
program = "/bin/zsh"

[font]
size = 21.0

[font.normal]
family = "MesloLGS Nerd Font Mono"
style = 'Regular'


[window]
decorations = "Buttonless"
opacity = 0.7
# blur = true
option_as_alt = "Both"
[window.padding]
x = 0
y = 0



