import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]

live_config_reload = true

[shell]
program = "/bin/zsh"

[colors]
draw_bold_text_with_bright_colors = false

[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 21.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font"
style = "Regular"

[font.bold_italic]
family = "Maple Mono"
style = "Bold Italic"

[font.italic]
family = "Maple Mono"
style = "Italic"



[mouse]
hide_when_typing = true

[scrolling]
history = 10000

[window]
opacity = 1.0
decorations = "Buttonless"
# blur = true
option_as_alt = "Both"
[window.padding]
x = 0
y = 0
