import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]
live_config_reload = true
[env]
TERM = "xterm-256color"

[cursor.style]
shape = "Beam"
# blinking = "Always"
 [colors]
draw_bold_text_with_bright_colors = true  

[shell]
program = "/bin/zsh"

[font]
size = 19.5


[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Maple Mono"
style = "Bold Italic"

[font.italic]
family = "Maple Mono"
style = "Italic"

[window]
decorations = "Buttonless"
# opacity = 0.9
# blur = true
option_as_alt = "Both"

[window.padding]
x = 0
y = 0
